---
title: "PanSolidv2 CNV Audit"
author: "Joe Shaw, Clinical Scientist (CS20980)"
date: today
date-format: "DD/MM/YYYY"
format: html
editor: visual
---

```{r}
#| label: packages
#| include: FALSE

library(tidyverse)
library(readxl)
library(here)

```

```{r}
#| label: functions
#| include: FALSE

source(here::here("functions/cnv_functions.R"))

```

```{r}
#| label: read-data
#| eval: FALSE
#| include: FALSE

# Manually add new worksheets to this Excel
pansolid_worksheets <- read_excel(here::here("data/pansolid_live_service_worksheets.xlsx"))

live_worksheets <- list(pansolid_worksheets$worksheet)

live_ws_filepaths <- live_worksheets |> 
  map(\(live_worksheets) get_annotated_filepaths(live_worksheets)) |> 
  flatten()

# Copy files into C drive directory

file.copy(from = live_ws_filepaths, 
          to = here::here("data/live_service_annotated_files/"))

copied_filepaths <- list.files(here::here("data/live_service_annotated_files/"),
                               full.names = TRUE)

# Two files don't have "Amplification" tabs
copied_filepaths <- copied_filepaths[-c(385,386)]

# Update the script to remove Excels without "Amplifications" tabs
copied_filepath_sheetnames <- copied_filepaths |> 
  map(\(copied_filepaths) get_amp_sheetname(copied_filepaths))

new_ws_amp_gene_results <- copied_filepaths |> 
  map(\(copied_filepaths) read_annotated_file_all_amp(copied_filepaths)) |>
  list_rbind()

new_ws_stdev_results <- copied_filepaths |> 
  map(\(copied_filepaths) read_annotated_file_stdev(copied_filepaths)) |>
  list_rbind()

```

```{r}
#| label: collate-data
#| eval: FALSE
#| include: FALSE

pansolid_cnv_collated_data <- new_ws_amp_gene_results |> 
      left_join(new_ws_stdev_results |> 
              select(file, st_dev_signal_adjusted_log2_ratios), 
              by = "file")

write.csv(pansolid_cnv_collated_data,
              here::here("data/pansolid_v2_cnv_service_results.csv"),
              row.names = FALSE)
    
```

```{r}
#| label: load-collated-data
#| include: FALSE

pansolid_cnv_collated_data <- read_csv(here::here("data/pansolid_v2_cnv_service_results.csv"))

```

In total, `r length(unique(pansolid_cnv_collated_data$labno))` samples are included in this audit.

```{r}
#| label: check-amplifications
#| include: FALSE

fold_change_threshold <- 2.8

live_results_mod <- pansolid_cnv_collated_data |> 
  mutate(result = case_when(
    
    max_region_fold_change >= fold_change_threshold ~"Amplification detected",
    
    max_region_fold_change < fold_change_threshold ~"No amplification detected"))

```

Here's the summary of amplifications detected for samples passing the quality filter (signal-adjusted noise metric below 1).

```{r}
#| label: summary-gene-amps-filter
#| echo: FALSE

summary_table_filter <- live_results_mod |> 
  filter(st_dev_signal_adjusted_log2_ratios < 1) |> 
  group_by(gene, result) |> 
  count() |> 
  pivot_wider(names_from = result, values_from = n, values_fill = 0)

knitr::kable(summary_table_filter)

```

These are the samples with amplifications detected.

```{r}
#| label: view-amps
#| echo: FALSE

amps_detected <- live_results_mod |> 
  filter(st_dev_signal_adjusted_log2_ratios < 1 &
           result == "Amplification detected") |> 
  select(labno, patient_name, gene, max_region_fold_change, 
         st_dev_signal_adjusted_log2_ratios) |> 
  arrange(gene, desc(max_region_fold_change))

knitr::kable(amps_detected)

```

{{< pagebreak >}}

And here's the overall view of gene fold changes.

```{r}
#| label: amps-plots
#| echo: FALSE

gene_fold_changes_plot <- ggplot(live_results_mod |> 
                                   filter(st_dev_signal_adjusted_log2_ratios < 1), 
                                 aes(x = gene, y = max_region_fold_change)) +
  geom_jitter(pch = 21, width = 0.2, alpha = 0.5, aes(fill = result)) +
  scale_fill_manual(values = c(safe_red, safe_blue)) +
  theme_bw() +
  labs(x = "", y = "Maximum region fold change") +
  geom_hline(yintercept = fold_change_threshold, linetype = "dashed")

gene_fold_changes_plot

```
