---
title: "ddPCR CNV Analysis"
author: "Joe Shaw"
date: today
date-format: "DD/MM/YYYY"
format: pdf
editor: visual
---

```{r}
#| label: packages
#| include: FALSE

library(tidyverse)
library(readxl)
library(here)
library(odbc)
library(DBI)
library(dbplyr)
library(ggpubr)

source(here::here("functions/cnv_functions.R"))

```

```{r}
#| label: ddpcr-analysis
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

failed_assays <- c("ERBB2 Ex3_1", "EGFR Ex2_1", "MYC Ex2_1")

normal_controls <- c("22000209", "22000666", "22000714", "22000552", "22002211")

ddpcr_ws <- read_biorad_csv("WS138419_analysed.csv") |> 
  mutate(category = case_when(
    
    sample %in% normal_controls ~"Normal",
    
    sample == "NTC" ~"NTC",
    
    TRUE ~"Patient"),
    
    gene = str_extract(string = experiment, pattern = "^(.+)\\s.+", group = 1))

draw_ddpcr_gene_plot <- function(df, gene_input) {
  
  output <- df |> 
    filter(!experiment %in% failed_assays) |> 
    filter(category != "NTC") |> 
    filter(!is.na(cnv)) |> 
    filter(gene == gene_input) |> 
    ggplot(aes(x = experiment, y = cnv)) +
      geom_point(aes(colour = category), size = 5, alpha = 0.5) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90)) +
      labs(y = "Copy number", x = "", title = gene_input) +
    geom_hline(yintercept = 2, linetype = "dashed")
  
  return(output)
  
}

draw_ddpcr_gene_plot(ddpcr_ws, "ERBB2")

```

{{< pagebreak >}}

```{r}
#| label: egfr-plot
#| echo: FALSE

draw_ddpcr_gene_plot(ddpcr_ws, "EGFR")

```

{{< pagebreak >}}

```{r}
#| label: myc-plot
#| echo: FALSE

draw_ddpcr_gene_plot(ddpcr_ws, "MYC") +
  ylim(0, 3)

```

{{< pagebreak >}}

```{r}
#| label: met-plot
#| echo: FALSE

draw_ddpcr_gene_plot(ddpcr_ws, "MET") +
  ylim(0, 7)

```
{{< pagebreak >}}


```{r}
#| label: braf-plot
#| echo: FALSE

draw_ddpcr_gene_plot(ddpcr_ws, "BRAF") +
  ylim(0, 7)
```
