---
title: "PanSolid Limit of Detection Experiment"
author: "Joe Shaw"
format: html
editor: visual
---

## Background

The PanSolid input is 16.75µl of 6ng/µl DNA (100.5ng total).

Dilutions of 20ul are required.

## Samples

"Tumour" sample: Seraseq® Solid Tumor CNV Mix, +12 copies (15.8ul)

"Normal" sample: Seraseq® DNA WT Mix (14.9ul)

## Calculations

```{r}
#| label: calculations
#| include: TRUE
#| message: FALSE

library(tidyverse)

tumour_stock_conc <- 10.9 

norm_stock_conc <- 28.8

total_c2 <- 6

total_v2 <- 18

total_ng <- total_c2 * total_v2

tumour_additional_copies <- 12

df <- data.frame("target_tumour_percent" = c(100, 50, 25, 12.5, 6.25, 3.12, 1.56, 0))

lod_calculations <- df |> 
  mutate(
    
    target_norm_percent = 100-target_tumour_percent,
    
    tumour_c1 = tumour_stock_conc * (target_tumour_percent/100),
    
    norm_c1 = norm_stock_conc * (target_norm_percent/100),
    
    # Calculate nanograms required of each sample (base and spike)
    
    tumour_ng = round(total_ng * (target_tumour_percent / 100), 1),
    
    norm_ng = round(total_ng * (target_norm_percent / 100), 1),
    
    total_ng = tumour_ng + norm_ng,
    
    # Calculate the starting volumes (v1) of each sample
    
    tumour_v1 = ifelse(tumour_ng ==0, 0, round(tumour_ng / tumour_c1, 1)),
    
    norm_v1 = ifelse(norm_ng == 0, 0, round(norm_ng / norm_c1, 1)),
    
    # Calculate the water volume required
    
    water_v1 = total_v2 - (tumour_v1 + norm_v1),
    
    final_v2 = water_v1 + tumour_v1 + norm_v1,
    
    final_c2 = round(((tumour_v1*tumour_c1) + (norm_v1*norm_c1)) / final_v2,0),
    
    # Calculate the additional number of copies in each mix
    
    norm_copies = round((target_norm_percent / 100) * 2,2),
    
    tumour_copies = round((target_tumour_percent / 100) * (tumour_additional_copies + 2),2),
    
    total_copies = round((norm_copies + tumour_copies),2),
    
    total_additional_copies = total_copies - 2,
    
    expected_fold_change = total_copies / 2
    
    )

knitr::kable(lod_calculations)

```

```{r}
#| label: export-results
#| include: FALSE

write.csv(lod_calculations, file = here::here("outputs/lod_calculations.csv"),
          row.names = FALSE)

```
