---
title: "ERBB2 Referrals"
author: "Joe Shaw"
date: today
date-format: "DD/MM/YYYY"
format: pdf
editor: visual
---

```{r}
#| label: packages
#| include: FALSE

library(tidyverse)
library(readxl)
library(here)
library(odbc)
library(DBI)
library(dbplyr)
library(ggpubr)

source(here::here("functions/cnv_functions.R"))

```

Here are the referrals for colorectal cancer testing (NGIS code M1) for 2023 from the Christie and Clatterbridge centres.

```{r}
#| label: erbb2-referrals
#| echo: FALSE

dlms_samples <- sample_tbl |> 
  select(c("LABNO", "DATE IN", "NGIS", "ConsultantAddress")) |> 
  collect()

m1_samples <- dlms_samples |> 
  filter(NGIS == "M1") |> 
  mutate(date = as_datetime(`DATE IN`))

m1_samples_2023 <- m1_samples |> 
  filter(date >= "2023-01-01 UTC" & date <= "2024-01-01 UTC")

clatterbridge_variants <- unique(grep(pattern = "clatter", 
                                      x = m1_samples_2023$ConsultantAddress,
                                      value = TRUE, ignore.case = TRUE))

christie_variants <- unique(grep(pattern = "christie", 
                                      x = m1_samples_2023$ConsultantAddress,
                                      value = TRUE, ignore.case = TRUE))

erbb2_referrals <- m1_samples_2023 |> 
  filter(ConsultantAddress %in% clatterbridge_variants |
           ConsultantAddress %in% christie_variants) |> 
  mutate(centre = case_when(
    
    ConsultantAddress %in% clatterbridge_variants ~"Clatterbridge",
    
     ConsultantAddress %in% christie_variants ~"Christie")) |> 
  group_by(centre) |> 
  summarise(per_year = n()) |> 
  mutate(per_month = round(per_year/12, 0))

knitr::kable(erbb2_referrals)

```

In total, there were `r nrow(m1_samples_2023)` samples with the M1 code received in 2023.
